import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopBar from "@/components/layout/TopBar";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang='en'>
                <head>
                    <title>Shousai</title>
                </head>
                <body className={`${inter.className} antialiased`}>
                    <TopBar />
                    {children}
                    <Analytics />
                </body>
            </html>
        </ClerkProvider>
    );
}
